### ISSUE TITLE
cjenkins does not run with python 3.x

### ISSUE THREAD

**Issue by uffejakobsen** [mariushe/cjenkins#4]
python3 cjenkins.py
  File "cjenkins.py", line 94
    print traceback.format_exc()
                  ^
SyntaxError: invalid syntax

**Comment by mariushe** [comment]
Hi.

Thanks for letting me know. I wrote it in 2.x so wasn't aware of the problems.

I've now done some adjustments so it should now work in v. 3.x.

Let me know how it goes.

Thanks!
